---
xnat_version: 1.8.9.2
xnat_pipeline_version: 1.8.3
xnat_archive_dir: "{{ xnat_root_dir }}/archive"
xnat_prearchive_dir: "{{ xnat_root_dir }}/prearchive"
xnat_cache_dir: "{{ xnat_root_dir }}/cache"
xnat_build_dir: "{{ xnat_root_dir }}/build"
xnat_ftp_dir: "{{ xnat_root_dir }}/ftp"
xnat_pipeline_dir: "{{ xnat_root_dir }}/pipeline"
xnat_inbox_dir: "{{ xnat_root_dir }}/inbox"
xnat_plugins_dir: "{{ xnat_home_dir }}/plugins"
xnat_config_dir: "{{ xnat_home_dir }}/config"
xnat_logs_dir: "{{ xnat_home_dir }}/logs"
xnat_work_dir: "{{ xnat_home_dir }}/work"
xnat_create_data_directory: true
xnat_link_data_directory: true

# Mail server settings
xnat_smtp_enabled: false
xnat_smtp_hostname: ""
xnat_smtp_port: "2525"
xnat_smtp_protocol: "smtp"
xnat_smtp_auth: ""
xnat_smtp_username: ""
xnat_smtp_password: ""
xnat_smtp_start_tls: "false"
xnat_smtp_ssl_trust: "*"
